SET search_path TO ares, public;

-- Engagement code (generated: ORG_SLUG-TYPE_CODE-YY-NN)
ALTER TABLE engagement ADD COLUMN code VARCHAR(60);
ALTER TABLE engagement ADD CONSTRAINT uq_engagement_code UNIQUE (code);

-- Finding code (generated: ENGAGEMENT_CODE-N)
ALTER TABLE finding ADD COLUMN code VARCHAR(70);
ALTER TABLE finding ADD CONSTRAINT uq_finding_code UNIQUE (code);

-- Detection code (generated by scanner: ENGAGEMENT_CODE-DETECT-N), nullable
ALTER TABLE detection ADD COLUMN code VARCHAR(80);
ALTER TABLE detection ADD CONSTRAINT uq_detection_code UNIQUE (code);
